services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dj_mako:local
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=mako
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: "on-failure"
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mako
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
