name: Build & Test

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver: docker

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: pull docker image
        run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: build
        run: docker-compose build

      - name: up
        run: docker-compose up -d
      - name: Run test suite
        run: |
          docker-compose run app pytest
