name: Pylinttt

on:
  # Trigger workflow on pull request, but only for PRs
  # merging into master and develop branches
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          **/*.py
          !**/migrations/*
          !**/envs/*
          !common/**/etree.py
        DOT: '...'
        THRESHOLD: 4
        DIFF_FILTER: 'AMRC'
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pylint
    - name: Creating pylint report
      id: pylint-report
      continue-on-error: true
      run: |
        pylint ${{ env.GIT_DIFF }} 2>&1 | tee report_pylint.txt
        
        body=$(cat report_pylint.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo ::set-output name=icon::":x:"
        [[ $body == *".py:"* || $body == *"***********"* ]] && title="**Please fix following pylint issues:**"
        [[ ${body:5} == "-----"* ]] && score="Good Job, Pylint Score:" && echo ::set-output name=status::success \
        && echo ::set-output name=icon::":white_check_mark:"
        echo ::set-output name=score::$score
        echo ::set-output name=title::$title
        echo ::set-output name=body::$body
      if: env.GIT_DIFF

    - name: Post report on PR
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          **pylint:** ${{ steps.pylint-report.outputs.icon }}
          ${{ steps.pylint-report.outputs.title }}
          ```
          ${{ steps.pylint-report.outputs.score }}${{ steps.pylint-report.outputs.body }}
          ```

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
      if: env.GIT_DIFF

    - name: Check Pylint Score
      run: |
        echo "Failed"
        echo ${{steps.pylint-report.outputs.score}}
        echo ${{steps.pylint-report.outputs.score < 4}}
        exit 1
      

      if: steps.pylint-report.outputs.score < 4
