name: Pylint

on:
  # Trigger workflow on pull request, but only for PRs
  # merging into master and develop branches
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
         pylint dj_mako

    - name: Lint with pylint
      working-directory: ./
      run: |
          echo  '${{ steps.files.outputs.files_updated }} ${{ steps.files.outputs.files_created }}'
          pip install -r requirements.txt
          OUTPUT = $(pylint ${{ steps.files.outputs.files_updated }} ${{ steps.files.outputs.files_created }}  --exit-zero --jobs=0)
          SCORE=$SCORE
          echo "Pylint finished with score: $SCORE"
          echo 'MESSAGE<<EOF' >> $GITHUB_ENV
          echo  "$OUTPUT"  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
